# Generated by Django 4.2 on 2023-04-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_deck_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['question']},
        ),
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='quizresult',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('question', 'deck')},
        ),
    ]
