# Generated by Django 4.2 on 2023-04-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_deck_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='answer_type',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='card',
            name='question_type',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
