# Generated by Django 4.2 on 2023-04-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_card_options_alter_deck_options_and_more'),
        ('quiz', '0003_card_answer_type_card_question_type'),
    ]

    operations = [
    ]
