# Generated by Django 4.2 on 2023-04-30 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_alter_card_options_alter_deck_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quiz.card'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='performance_type',
            field=models.PositiveSmallIntegerField(choices=[(-2, 'Very bad'), (-1, 'Bad'), (1, 'Moderate'), (2, 'Good'), (3, 'Very good')]),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
