# Generated by Django 4.2 on 2023-04-30 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_merge_20230429_1805'),
        ('quiz', '0005_decktag_alter_deck_tags'),
    ]

    operations = [
    ]
