# Generated by Django 4.2 on 2023-05-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_merge_20230430_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='performance_type',
            field=models.SmallIntegerField(choices=[(-2, 'Very bad'), (-1, 'Bad'), (1, 'Moderate'), (2, 'Good'), (3, 'Very good')]),
        ),
    ]
