# Generated by Django 4.2 on 2023-05-09 21:33

from django.db import migrations, models
import django.db.models.deletion
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_merge_20230430_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.deck')),
            ],
            options={
                'ordering': ['created_at'],
            },
            bases=(quiz.models.ModelPermissionMixin, models.Model),
        ),
    ]
