# Generated by Django 4.2 on 2023-05-10 18:07

from django.db import migrations, models
import django.db.models.deletion
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_storedeck'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDeckDownloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.deck')),
            ],
            bases=(quiz.models.ModelPermissionMixin, models.Model),
        ),
    ]
