# Generated by Django 4.2 on 2023-05-10 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_storedeckdownloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedeck',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
