# Generated by Django 4.2 on 2023-05-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_quizresult_performance_type'),
        ('quiz', '0010_storedeck_downloads_delete_storedeckdownloads'),
    ]

    operations = [
    ]
