# Generated by Django 4.2 on 2023-05-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_merge_20230511_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='performance_type',
            field=models.SmallIntegerField(choices=[(-2, 'VERY_BAD'), (-1, 'BAD'), (1, 'MODERATE'), (2, 'GOOD'), (3, 'VERY_GOOD')]),
        ),
    ]
